version: '3'
services:
  postgres:
    image: "postgres:11.7"
    ports: 
        - 5432:5432
    environment:
        - POSTGRES_USER=psgr_user
        - POSTGRES_PASSWORD=psgr_password
        - POSTGRES_DB=psgr_db
    volumes:
        - psgr-data:/var/lib/postgresql/data
  mysql:
    image: "mysql:latest"
    ports: 
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=mysql
    volumes:
        - mysql-data:/var/lib/mysql
  redis:
    image: "bitnami/redis"
    ports: 
        - 6379:6379
    environment:
        - ALLOW_EMPTY_PASSWORD=1
    volumes:
        - redis-data:/bitnami/redis/data
volumes:
    psgr-data: 
    redis-data: 
    mysql-data: 